# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grin < Formula
  desc "Make INI files greppable"
  homepage "https://github.com/Yoshi325/grin"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Yoshi325/grin/releases/download/v0.1.5/grin_0.1.5_darwin_amd64.tar.gz"
      sha256 "60857cd1cdcf006eb16e323a594acf4d544e9276a79e683f5559004029d14e3f"

      def install
        bin.install "grin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Yoshi325/grin/releases/download/v0.1.5/grin_0.1.5_darwin_arm64.tar.gz"
      sha256 "9362192a1922fbecca2ed00d1ddb8c8f6575b333054a3371f2378ec5aaea67aa"

      def install
        bin.install "grin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yoshi325/grin/releases/download/v0.1.5/grin_0.1.5_linux_amd64.tar.gz"
      sha256 "b9640a0274b339741289fd704fa10a13d6bbe997fb79430eec5ee8e0732342a0"
      def install
        bin.install "grin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yoshi325/grin/releases/download/v0.1.5/grin_0.1.5_linux_arm64.tar.gz"
      sha256 "86bd35c318e65c182c0167e6711d69134b560148d70d9451013a2940ca6866af"
      def install
        bin.install "grin"
      end
    end
  end

  test do
    assert_match "grin version", shell_output("#{bin}/grin --version")
  end
end
