# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grin < Formula
  desc "Make INI files greppable"
  homepage "https://yoshi325.github.io/grin/"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Yoshi325/grin/releases/download/v0.1.7/grin_0.1.7_darwin_amd64.tar.gz"
      sha256 "fbeb2afe72cedd8dcdcfb0470a7fbe392ded67da0102247e44b41fc57e8d7bf7"

      def install
        bin.install "grin"
        man1.install "doc/grin.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Yoshi325/grin/releases/download/v0.1.7/grin_0.1.7_darwin_arm64.tar.gz"
      sha256 "57cf0b5da0f321df8b9c17b85d9a66fa1d3885489256383921c41f2d9b60782b"

      def install
        bin.install "grin"
        man1.install "doc/grin.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yoshi325/grin/releases/download/v0.1.7/grin_0.1.7_linux_amd64.tar.gz"
      sha256 "7af66a07fef21788900d3e39d63fa0628efde67f64e08119d63f113f32466527"
      def install
        bin.install "grin"
        man1.install "doc/grin.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yoshi325/grin/releases/download/v0.1.7/grin_0.1.7_linux_arm64.tar.gz"
      sha256 "b41d2d529d257926e3bd66fc5c7aa183fa86cb1c64056c2b196aa27247307bfe"
      def install
        bin.install "grin"
        man1.install "doc/grin.1"
      end
    end
  end

  test do
    assert_match "grin version", shell_output("#{bin}/grin --version")
  end
end
