# This file was generated by GoReleaser. DO NOT EDIT.
cask "grin" do
  name "grin"
  desc "Make INI files greppable"
  homepage "https://github.com/Yoshi325/grin"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grin"

  on_macos do
    on_intel do
      url "https://github.com/Yoshi325/grin/releases/download/v#{version}/grin_#{version}_darwin_amd64.tar.gz"
      sha256 "fc4114b549e8f30e009f74649432f55d7c3d1057041275c1e393750f4b9c2e9b"
    end
    on_arm do
      url "https://github.com/Yoshi325/grin/releases/download/v#{version}/grin_#{version}_darwin_arm64.tar.gz"
      sha256 "be67994d836beafd2cb967b0580635d2e2c94cdaabfb8475d8973a531ebc0567"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Yoshi325/grin/releases/download/v#{version}/grin_#{version}_linux_amd64.tar.gz"
      sha256 "fa1893c74408c2f3939c4887480ad9e4d14167001e9d79ab56d10373068e90ed"
    end
    on_arm do
      url "https://github.com/Yoshi325/grin/releases/download/v#{version}/grin_#{version}_linux_arm64.tar.gz"
      sha256 "411c6ea2f09a2ec056ff9a498f7da15b6b50d241a2ea50e8820722155306b9f5"
    end
  end

  # No zap stanza required
end
